version: '3.3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports: 
      - 27017:27017

  api-nestjs:
    image: node:20.9.0
    container_name: red-social-api-nestjs
    working_dir: /usr/main
    volumes:
      - ./api-nestjs:/usr/main
    ports:
      - 3000:3000
    command: bash -c "npm install && npm run start:dev"