version: '3.3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports: 
      - 27017:27017

  api:
    image: node:20.9.0
    container_name: red-social-api
    working_dir: /usr/index
    volumes:
      - ./api:/usr/index
    ports:
      - 3001:3001
    command: bash -c "npm install && npm start"